
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtgxsngjmzugzdbbbxph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0Z3hzbmdqbXp1Z3pkYmJieHBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNDkwMDgsImV4cCI6MjA1NjkyNTAwOH0.SRuu-GP5zq4OjTgnHBmvAbm1j0dR3e0bLJ8hO-Cz5pI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// GitHub OAuth helper function
export const signInWithGitHub = async () => {
  const { data, error } = await supabase.auth.signInWithOAuth({
    provider: 'github',
    options: {
      redirectTo: `${window.location.origin}/`
    }
  });
  
  return { data, error };
};

// Logout helper function
export const signOut = async () => {
  const { error } = await supabase.auth.signOut();
  return { error };
};
